server:
  port: 9999

spring:
  mvc:
    log-request-details: true
  liquibase:
    enabled: false
  datasource:
    url: jdbc:h2:file:./db/db
    # url: jdbc:h2:file:/app/db/db
    # url: jdbc:h2:file:/var/lib/agorohov.com/tgbot/irregularverbs/appdb
    username: u
    password:
  jpa:
    open-in-view: true
    hibernate:
      # ddl-auto: validate
      ddl-auto: update
#    вывод sql в консоль
      show-sql:
        false
    properties:
      hibernate:
        # форматирование вывода запросов в консоль
        format_sql: true
        # включает генерирование статистики о запросах на уровне Hibernate
        # generate_statistics: true
        # включает сортировку запросов по имени таблицы.
        # В случае если инсерты не отсортированы по имени таблицы, 
        # они не могут быть объеденины в один батч и будут разделены на несколько батчей
        # order_inserts: true
        # jdbc.batch_size: 1000
        # enable_lazy_load_no_trans: true

  h2:
    console:
      enabled: true
    
bot:
    name: ${IRRVERBS_BOT_NAME}
    token: ${IRRVERBS_BOT_TOKEN}
    owner: ${IRRVERBS_BOT_OWNER}
    
# cron:
  # секунды / минуты / часы / день / месяц / день недели  
  # scheduler: 0 34 12 * * *